apiVersion: monteur.wolt.com/v1beta1
kind: Aurora
spec:
  - name: db14
    engine: "aurora-postgresql"
    engineMode: "provisioned"
    psqlVersion: "14.10"
    mountPathSuffix: pg14
    extensions:
      - name: pg_stat_statements
      - name: plpgsql
      - name: dblink
        schema: accounting-service
      - name: postgres_fdw
        schema: accounting-service
      - name: pg_cron
      - name: pg_partman
        schema: partman
    tags:
      aws-backup: "tier3"
    publications:
      - name: debezium_cdc_pub
        owner: debezium
        allTables: true
    overrides:
      - env: dev
        stage: development
        extraIngressRules:
          sgIDs:
            - "sg-xxx"
      - env: prod
        stage: production
        extraIngressRules:
          sgIDs:
            - "sg-xxx"
