apiVersion: monteur.wolt.com/v1beta1
kind: Aurora
spec:
  - name: db
    engine: "aurora-postgresql"
    engineMode: "provisioned"
    psqlVersion: "15.3"
    storageEncrypted: true
    overrides:
      - env: dev
        stage: development
      - env: prod
        stage: production